axis_linear: 1  # Left thumb stick vertical
scale_linear: 1.2
scale_linear_turbo: 2.2

axis_angular: 0  # Left thumb stick horizontal
scale_angular: 0.8
scale_angular_turbo: 1.6

enable_button: 2  # Left trigger button
enable_turbo_button: 5  # Right trigger button
